resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

serviceMonitor:
  enabled: true

nodeSelector:
  karpenter.k8s.aws/instance-gpu-manufacturer: nvidia

tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
