apiVersion: eks.amazonaws.com/v1
kind: NodeClass
metadata:
  name: gpu-inf
  labels:
    guide: eks-docs-inf
spec:
  role: ${node_iam_role_name}
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
        kubernetes.io/role/internal-elb: '1'
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: ${cluster_name}
%{ if capacity_reservation_id != "" }  
  capacityReservationSelectorTerms:
    - id: ${capacity_reservation_id}
%{ endif ~}
